# Generated by Django 2.1.4 on 2018-12-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtistId', models.IntegerField()),
                ('ArtistName', models.CharField(max_length=30)),
                ('TrackName', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=30)),
                ('GenreName', models.CharField(max_length=30)),
                ('ReleaseDate', models.DateField()),
            ],
        ),
    ]
