# Generated by Django 2.1.4 on 2018-12-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181206_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Track',
        ),
    ]
